/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahorcadoswing;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author FP
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form Ahorcado
     */
    public Ahorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonA = new javax.swing.JToggleButton();
        jToggleButtonB = new javax.swing.JToggleButton();
        jToggleButtonC = new javax.swing.JToggleButton();
        jToggleButtonD = new javax.swing.JToggleButton();
        jToggleButtonF = new javax.swing.JToggleButton();
        jToggleButtonE = new javax.swing.JToggleButton();
        jToggleButtonL = new javax.swing.JToggleButton();
        jToggleButtonK = new javax.swing.JToggleButton();
        jToggleButtonJ = new javax.swing.JToggleButton();
        jToggleButtonI = new javax.swing.JToggleButton();
        jToggleButtonH = new javax.swing.JToggleButton();
        jToggleButtonG = new javax.swing.JToggleButton();
        jToggleButtonM = new javax.swing.JToggleButton();
        jToggleButtonN = new javax.swing.JToggleButton();
        jToggleButtonNY = new javax.swing.JToggleButton();
        jToggleButtonO = new javax.swing.JToggleButton();
        jToggleButtonP = new javax.swing.JToggleButton();
        jToggleButtonQ = new javax.swing.JToggleButton();
        jToggleButtonR = new javax.swing.JToggleButton();
        jToggleButtonS = new javax.swing.JToggleButton();
        jToggleButtonT = new javax.swing.JToggleButton();
        jToggleButtonU = new javax.swing.JToggleButton();
        jToggleButtonV = new javax.swing.JToggleButton();
        jToggleButtonW = new javax.swing.JToggleButton();
        jToggleButtonX = new javax.swing.JToggleButton();
        jToggleButtonY = new javax.swing.JToggleButton();
        jToggleButtonZ = new javax.swing.JToggleButton();
        jLabelImagen = new javax.swing.JLabel();
        jPasswordFieldPalabra = new javax.swing.JPasswordField();
        jButtonNuevaPartida = new javax.swing.JButton();
        jButtonAsignarPalabra = new javax.swing.JButton();
        jLabelPalabraOculta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonA.setText("A");
        jToggleButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAActionPerformed(evt);
            }
        });
        jToggleButtonA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButtonAKeyPressed(evt);
            }
        });

        jToggleButtonB.setText("B");
        jToggleButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBActionPerformed(evt);
            }
        });

        jToggleButtonC.setText("C");

        jToggleButtonD.setText("D");

        jToggleButtonF.setText("F");

        jToggleButtonE.setText("E");

        jToggleButtonL.setText("L");

        jToggleButtonK.setText("K");

        jToggleButtonJ.setText("J");

        jToggleButtonI.setText("I");

        jToggleButtonH.setText("H");
        jToggleButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHActionPerformed(evt);
            }
        });

        jToggleButtonG.setText("G");

        jToggleButtonM.setText("M");

        jToggleButtonN.setText("N");
        jToggleButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNActionPerformed(evt);
            }
        });

        jToggleButtonNY.setText("Ñ");

        jToggleButtonO.setText("O");

        jToggleButtonP.setText("P");

        jToggleButtonQ.setText("Q");

        jToggleButtonR.setText("R");

        jToggleButtonS.setText("S");
        jToggleButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSActionPerformed(evt);
            }
        });

        jToggleButtonT.setText("T");

        jToggleButtonU.setText("U");

        jToggleButtonV.setText("V");

        jToggleButtonW.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jToggleButtonW.setText("W");

        jToggleButtonX.setText("X");

        jToggleButtonY.setText("Y");
        jToggleButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonYActionPerformed(evt);
            }
        });

        jToggleButtonZ.setText("Z");

        jPasswordFieldPalabra.setToolTipText("Palabra para jugar");

        jButtonNuevaPartida.setText("Nueva partida");

        jButtonAsignarPalabra.setText("Asignar palabra");
        jButtonAsignarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarPalabraActionPerformed(evt);
            }
        });

        jLabelPalabraOculta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordFieldPalabra)
                    .addComponent(jButtonAsignarPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNuevaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jToggleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jToggleButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButtonNY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabelPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordFieldPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAsignarPalabra)
                        .addGap(185, 185, 185)
                        .addComponent(jButtonNuevaPartida))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonNY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonBActionPerformed

    private void jToggleButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHActionPerformed

    private void jToggleButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonNActionPerformed

    private void jToggleButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonSActionPerformed

    private void jToggleButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonYActionPerformed

    private void jToggleButtonAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButtonAKeyPressed
        
    }//GEN-LAST:event_jToggleButtonAKeyPressed

    private void jToggleButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAActionPerformed
        jLabelImagen.setIcon(new ImageIcon(getClass().getResource("../img/ahorcado1.jpg")));
        jToggleButtonA.setBackground(Color.red);
        //jToggleButtonA.setEnabled(false);
        
    }//GEN-LAST:event_jToggleButtonAActionPerformed

    private void jButtonAsignarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarPalabraActionPerformed
        //jPasswordFieldPalabra
        palabra = new char[jPasswordFieldPalabra.getPassword().length];
        palabra = jPasswordFieldPalabra.getPassword();
        for (int i = 0; i < palabra.length; i++) {
            palabraOcultaMostrar += "_";
        }
        jLabelPalabraOculta.setText(palabraOcultaMostrar);
    }//GEN-LAST:event_jButtonAsignarPalabraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }
    private String palabraOcultaMostrar = "";
    private char[] palabra;
    private int fallos = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignarPalabra;
    private javax.swing.JButton jButtonNuevaPartida;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPalabraOculta;
    private javax.swing.JPasswordField jPasswordFieldPalabra;
    private javax.swing.JToggleButton jToggleButtonA;
    private javax.swing.JToggleButton jToggleButtonB;
    private javax.swing.JToggleButton jToggleButtonC;
    private javax.swing.JToggleButton jToggleButtonD;
    private javax.swing.JToggleButton jToggleButtonE;
    private javax.swing.JToggleButton jToggleButtonF;
    private javax.swing.JToggleButton jToggleButtonG;
    private javax.swing.JToggleButton jToggleButtonH;
    private javax.swing.JToggleButton jToggleButtonI;
    private javax.swing.JToggleButton jToggleButtonJ;
    private javax.swing.JToggleButton jToggleButtonK;
    private javax.swing.JToggleButton jToggleButtonL;
    private javax.swing.JToggleButton jToggleButtonM;
    private javax.swing.JToggleButton jToggleButtonN;
    private javax.swing.JToggleButton jToggleButtonNY;
    private javax.swing.JToggleButton jToggleButtonO;
    private javax.swing.JToggleButton jToggleButtonP;
    private javax.swing.JToggleButton jToggleButtonQ;
    private javax.swing.JToggleButton jToggleButtonR;
    private javax.swing.JToggleButton jToggleButtonS;
    private javax.swing.JToggleButton jToggleButtonT;
    private javax.swing.JToggleButton jToggleButtonU;
    private javax.swing.JToggleButton jToggleButtonV;
    private javax.swing.JToggleButton jToggleButtonW;
    private javax.swing.JToggleButton jToggleButtonX;
    private javax.swing.JToggleButton jToggleButtonY;
    private javax.swing.JToggleButton jToggleButtonZ;
    // End of variables declaration//GEN-END:variables
}
